---
swagger: '2.0'
info:
  title: Autocomplete API
  version: v1
paths:
  "/books_autocomplete":
    get:
      summary: Retrieves a list of books
      tags:
      - Books
      produces:
      - application/json
      parameters:
      - name: q
        in: query
        type: string
        description: The string to be completed
      responses:
        '200':
          description: successful query
          schema:
            oneOf:
            - type: string
              example: 'null'
            - type: array
              items: {}
            - type: object
              properties:
                text:
                  type: string
                _index:
                  type: string
                _type:
                  type: string
                _id:
                  type: string
                _score:
                  type: string
                _source:
                  type: object
                  properties:
                    reference:
                      type: string
                    suggest:
                      type: object
                      properties:
                        input:
                          type: array
                          items: {}
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
